// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job/jobpb/job.proto

package jobpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecruiterId          string   `protobuf:"bytes,2,opt,name=recruiter_id,json=recruiterId,proto3" json:"recruiter_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_0048218e2888fd80, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetRecruiterId() string {
	if m != nil {
		return m.RecruiterId
	}
	return ""
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Job) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Job) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CreateJobRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0048218e2888fd80, []int{1}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobResponse struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0048218e2888fd80, []int{2}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type ReadJobRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadJobRequest) Reset()         { *m = ReadJobRequest{} }
func (m *ReadJobRequest) String() string { return proto.CompactTextString(m) }
func (*ReadJobRequest) ProtoMessage()    {}
func (*ReadJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0048218e2888fd80, []int{3}
}

func (m *ReadJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJobRequest.Unmarshal(m, b)
}
func (m *ReadJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJobRequest.Marshal(b, m, deterministic)
}
func (m *ReadJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJobRequest.Merge(m, src)
}
func (m *ReadJobRequest) XXX_Size() int {
	return xxx_messageInfo_ReadJobRequest.Size(m)
}
func (m *ReadJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJobRequest proto.InternalMessageInfo

func (m *ReadJobRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type ReadJobResponse struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadJobResponse) Reset()         { *m = ReadJobResponse{} }
func (m *ReadJobResponse) String() string { return proto.CompactTextString(m) }
func (*ReadJobResponse) ProtoMessage()    {}
func (*ReadJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0048218e2888fd80, []int{4}
}

func (m *ReadJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJobResponse.Unmarshal(m, b)
}
func (m *ReadJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJobResponse.Marshal(b, m, deterministic)
}
func (m *ReadJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJobResponse.Merge(m, src)
}
func (m *ReadJobResponse) XXX_Size() int {
	return xxx_messageInfo_ReadJobResponse.Size(m)
}
func (m *ReadJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJobResponse proto.InternalMessageInfo

func (m *ReadJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "job.Job")
	proto.RegisterType((*CreateJobRequest)(nil), "job.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "job.CreateJobResponse")
	proto.RegisterType((*ReadJobRequest)(nil), "job.ReadJobRequest")
	proto.RegisterType((*ReadJobResponse)(nil), "job.ReadJobResponse")
}

func init() { proto.RegisterFile("job/jobpb/job.proto", fileDescriptor_0048218e2888fd80) }

var fileDescriptor_0048218e2888fd80 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x56, 0x5b, 0x92, 0xd2, 0x2b, 0x2a, 0xe0, 0xfe, 0xc8, 0xca, 0x04, 0x59, 0x60, 0x21, 0x95,
	0x0a, 0x13, 0x23, 0x4c, 0xcd, 0x18, 0x36, 0x96, 0xaa, 0x8e, 0x4f, 0xc8, 0x11, 0xca, 0x05, 0xc7,
	0x41, 0x62, 0xe1, 0x41, 0x78, 0x5a, 0x94, 0x4b, 0x1a, 0xb5, 0x1d, 0x60, 0x89, 0xf4, 0xfd, 0xf9,
	0xbe, 0xcb, 0xc1, 0x34, 0x23, 0xb5, 0xcc, 0x48, 0x15, 0xfc, 0x8d, 0x0a, 0x4b, 0x8e, 0xc4, 0x20,
	0x23, 0x15, 0xfe, 0xf4, 0x60, 0x10, 0x93, 0x12, 0x13, 0xe8, 0x1b, 0x2d, 0x7b, 0x57, 0xbd, 0xdb,
	0x51, 0xd2, 0x37, 0x5a, 0x5c, 0xc3, 0x99, 0xc5, 0xd4, 0x56, 0xc6, 0xa1, 0xdd, 0x18, 0x2d, 0xfb,
	0xac, 0x8c, 0x3b, 0x6e, 0xad, 0xc5, 0x0c, 0x3c, 0x67, 0xdc, 0x3b, 0xca, 0x01, 0x6b, 0x0d, 0x10,
	0x12, 0x86, 0x29, 0xe5, 0x0e, 0x73, 0x27, 0x4f, 0x98, 0xdf, 0x41, 0xb1, 0x00, 0xdf, 0xe2, 0x9b,
	0xa1, 0x5c, 0x7a, 0x2c, 0xb4, 0xa8, 0x49, 0x54, 0xb9, 0xb3, 0x5f, 0xd2, 0xdf, 0x25, 0x18, 0x86,
	0x11, 0x5c, 0x3c, 0x5b, 0xdc, 0x3a, 0x8c, 0x49, 0x25, 0xf8, 0x51, 0x61, 0xe9, 0x44, 0x00, 0x75,
	0x6f, 0x6e, 0x3a, 0x5e, 0x9d, 0x46, 0xf5, 0x3a, 0xb5, 0xca, 0xcb, 0x2c, 0xe1, 0x72, 0xcf, 0x5f,
	0x16, 0x94, 0x97, 0xf8, 0x67, 0xe0, 0x06, 0x26, 0x09, 0x6e, 0xf5, 0xde, 0xf3, 0x73, 0xf0, 0x33,
	0x52, 0x9b, 0xee, 0x5f, 0x78, 0x19, 0xa9, 0xb5, 0x0e, 0xef, 0xe0, 0xbc, 0x33, 0xfe, 0xff, 0xee,
	0xea, 0x1b, 0x20, 0x26, 0xf5, 0x82, 0xf6, 0xd3, 0xa4, 0x28, 0x1e, 0x61, 0xd4, 0xd5, 0x12, 0x73,
	0x76, 0x1e, 0xaf, 0x15, 0x2c, 0x8e, 0xe9, 0x76, 0xca, 0x03, 0x0c, 0xdb, 0xc1, 0x62, 0xca, 0x96,
	0xc3, 0xbe, 0xc1, 0xec, 0x90, 0x6c, 0x52, 0x4f, 0xc3, 0x57, 0x8f, 0xaf, 0xad, 0x7c, 0x3e, 0xf5,
	0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xc7, 0xb2, 0x87, 0x01, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	ReadJob(ctx context.Context, in *ReadJobRequest, opts ...grpc.CallOption) (*ReadJobResponse, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/job.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ReadJob(ctx context.Context, in *ReadJobRequest, opts ...grpc.CallOption) (*ReadJobResponse, error) {
	out := new(ReadJobResponse)
	err := c.cc.Invoke(ctx, "/job.JobService/ReadJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	ReadJob(context.Context, *ReadJobRequest) (*ReadJobResponse, error)
}

// UnimplementedJobServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (*UnimplementedJobServiceServer) CreateJob(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (*UnimplementedJobServiceServer) ReadJob(ctx context.Context, req *ReadJobRequest) (*ReadJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadJob not implemented")
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ReadJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ReadJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/ReadJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ReadJob(ctx, req.(*ReadJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "ReadJob",
			Handler:    _JobService_ReadJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job/jobpb/job.proto",
}
